add South-Tyrolean layers
simon04/tyrolean-map pull request #3
Opened 2017-01-28 21:16 UTC by tyrasd

for #1

2017-01-29 16:34 UTC, simon04 requested changes
Great! Thank you for your contribution. Please fix the attribution and I'll merge.

2017-01-29 16:34 UTC, simon04 commented on app.js
> +    attribution: attribution
This attribution is wrong.

2017-01-29 16:34 UTC, simon04 commented on app.js
> +  {id: 'P_BZ_BASEMAP_TOPO', title: 'South Tyrol Base Map'},
I would have used German layer names, but I'm happy to take the English ones as well. :smile:

2017-01-30 10:15 UTC, tyrasd commented on app.js
> +    attribution: attribution
fixed!

2017-01-30 10:17 UTC, tyrasd commented on app.js
> +  {id: 'P_BZ_BASEMAP_TOPO', title: 'South Tyrol Base Map'},
feel free to tweak the names! (I've chosen English since the alternative German+Italian would have been a bit long.)

2017-01-31 09:30 UTC, simon04 approved these changes

2017-01-31 09:31 UTC, merged